[[library]]
name = "libqt6concurrent"
file = "libQt6Concurrent"

[[library]]
name = "libqt6core"
file = "libQt6Core"

[[library]]
name = "libqt6dbus"
file = "libQt6DBus"

[[library]]
name = "libqt6gui"
file = "libQt6Gui"

[[library]]
name = "libqt6network"
file = "libQt6Network"

[[library]]
name = "libqt6opengl"
file = "libQt6OpenGL"

[[library]]
name = "libqt6printsupport"
file = "libQt6PrintSupport"

[[library]]
name = "libqt6sql"
file = "libQt6Sql"

[[library]]
name = "libqt6test"
file = "libQt6Test"

[[library]]
name = "libqt6widgets"
file = "libQt6Widgets"

[[library]]
name = "libqt6xml"
file = "libQt6Xml"
