[__config__]
oldver = "nvchecker-old.txt"
newver = "nvchecker-new.txt"
max_concurrency = 1

[c-ares]
source = "archpkg"
archpkg = "c-ares"

[nghttp2]
source = "archpkg"
archpkg = "libnghttp2"

[curl]
source = "archpkg"
archpkg = "curl"

[ssl]
source = "archpkg"
archpkg = "openssl"

[zlib]
source = "archpkg"
archpkg = "zlib"

[xz]
source = "archpkg"
archpkg = "xz"

[bzip]
source = "archpkg"
archpkg = "bzip2"

[zstd]
source = "archpkg"
archpkg = "zstd"

[libarchive]
source = "archpkg"
archpkg = "libarchive"

[gpgerror]
source = "archpkg"
archpkg = "libgpg-error"

[libassuan]
source = "archpkg"
archpkg = "libassuan"

[gpgme]
source = "archpkg"
archpkg = "gpgme"
