[[library]]
name = "libavcodec"

[[library]]
name = "libavdevice"

[[library]]
name = "libavfilter"

[[library]]
name = "libavformat"

[[library]]
name = "libavutil"

[[library]]
name = "libpostproc"

[[library]]
name = "libswresample"

[[library]]
name = "libswscale"

[[binary]]
name = "ffmpeg"

[[binary]]
name = "ffprobe"
