[[library]]
name = "librsvg"
file = "librsvg-2"

[[binary]]
name = "rsvg_convert"
file = "rsvg-convert"

[[file]]
name = "libpixbufloader_svg"
file = "/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so"
