sudo: required

services:
- docker

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - p7zip
  - wine
  - wine-mono
  - wine_gecko
  - xorg-xwininfo
  - wqy-microhei
  - adobe-source-han-sans-cn-fonts
  - adobe-source-han-serif-cn-fonts
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-libpulse
  - lib32-openal
  - lib32-mpg123
  - lib32-gnutls
  script:
  - "makepkg"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
