version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "config",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch",
    "0002-Default-to-maximum-amount-of-ASLR-bits.patch",
    "0003-skip-simpledrm-if-nvidia-drm.modeset=1-is.patch",
]
SPDX-FileCopyrightText = "Linux Kernel contributors"
SPDX-License-Identifier = "GPL-2.0-only"
