version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-only-build-the-module-in-dkms.conf.patch",
]
SPDX-FileCopyrightText ="Eli Schwartz <eschwartz@archlinux.org, Jonathon Fernyhough <jonathon@m2x.dev>"
SPDX-License-Identifier = "CDDL-1.0"
