[[library]]
name = "libwand"
file = "libMagickWand-7.Q16HDRI.so"

[[binary]]
name = "identify"

[[binary]]
name = "imagemagick_convert"
file = "convert"

[[binary]]
name = "mogrify"

[[binary]]
name = "montage"
