version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "add-missing-dnd-kit-sortable.patch",
    "proton-authenticator.desktop",
]
SPDX-FileCopyrightText = "Proton AG"
SPDX-License-Identifier = "GPL-3.0-or-later"
