version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fortran-riscv64.patch",
    "makepkg-riscv64.patch",
    "pacman-extra-riscv64.patch",
    "sogrep-riscv64.patch",
]
SPDX-FileCopyrightText = "devtools-riscv64 contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
